//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeppAplicationSunat.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Agregar(
                    string Ruc, 
                    string Nombre, 
                    string TipoDocumento, 
                    string Estado, 
                    string Condicion, 
                    string Direccion, 
                    string Ubigeo, 
                    string ViaTipo, 
                    string ViaNombre, 
                    string ZonaCodi, 
                    string ZonaTipo, 
                    string numero, 
                    string Interior, 
                    string Lote, 
                    string Dpto, 
                    string Manzana, 
                    string Kilometro, 
                    string Distrito, 
                    string Provincia, 
                    string Departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AgregarAsync(
                    string Ruc, 
                    string Nombre, 
                    string TipoDocumento, 
                    string Estado, 
                    string Condicion, 
                    string Direccion, 
                    string Ubigeo, 
                    string ViaTipo, 
                    string ViaNombre, 
                    string ZonaCodi, 
                    string ZonaTipo, 
                    string numero, 
                    string Interior, 
                    string Lote, 
                    string Dpto, 
                    string Manzana, 
                    string Kilometro, 
                    string Distrito, 
                    string Provincia, 
                    string Departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WeppAplicationSunat.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WeppAplicationSunat.ServiceReference1.WebService1Soap>, WeppAplicationSunat.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public bool Agregar(
                    string Ruc, 
                    string Nombre, 
                    string TipoDocumento, 
                    string Estado, 
                    string Condicion, 
                    string Direccion, 
                    string Ubigeo, 
                    string ViaTipo, 
                    string ViaNombre, 
                    string ZonaCodi, 
                    string ZonaTipo, 
                    string numero, 
                    string Interior, 
                    string Lote, 
                    string Dpto, 
                    string Manzana, 
                    string Kilometro, 
                    string Distrito, 
                    string Provincia, 
                    string Departamento) {
            return base.Channel.Agregar(Ruc, Nombre, TipoDocumento, Estado, Condicion, Direccion, Ubigeo, ViaTipo, ViaNombre, ZonaCodi, ZonaTipo, numero, Interior, Lote, Dpto, Manzana, Kilometro, Distrito, Provincia, Departamento);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarAsync(
                    string Ruc, 
                    string Nombre, 
                    string TipoDocumento, 
                    string Estado, 
                    string Condicion, 
                    string Direccion, 
                    string Ubigeo, 
                    string ViaTipo, 
                    string ViaNombre, 
                    string ZonaCodi, 
                    string ZonaTipo, 
                    string numero, 
                    string Interior, 
                    string Lote, 
                    string Dpto, 
                    string Manzana, 
                    string Kilometro, 
                    string Distrito, 
                    string Provincia, 
                    string Departamento) {
            return base.Channel.AgregarAsync(Ruc, Nombre, TipoDocumento, Estado, Condicion, Direccion, Ubigeo, ViaTipo, ViaNombre, ZonaCodi, ZonaTipo, numero, Interior, Lote, Dpto, Manzana, Kilometro, Distrito, Provincia, Departamento);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
